<h1> Using Scikit learn

In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import add_dummy_feature
iris=load_iris(as_frame=True)
X=iris.data
Y=iris.target_names[iris.target]

In [2]:
from sklearn.model_selection import train_test_split
trainx,testx,trainy,testy= train_test_split(X,Y,test_size=0.5)
validx=testx[:len(testx)//2]
validy=testy[:len(testy)//2]
testx=testx[len(testx)//2:]
testx=testy[len(testy)//2:]

In [3]:
from sklearn.linear_model import LogisticRegression
import numpy as np
lr=LogisticRegression()

In [4]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
validy_encoded=ohe.fit_transform(validy.reshape(-1,1),)

In [5]:
lr.fit(trainx,trainy)

LogisticRegression()

In [6]:
temp=lr.predict_proba(validx)-validy_encoded


In [7]:
temp=add_dummy_feature(temp)

In [8]:
validx.T@temp

0         1         2         3
sepal length (cm)  208.6  2.783671 -5.167718  2.384048
sepal width (cm)   113.6  0.917234 -1.893831  0.976597
petal length (cm)  124.6  2.653854 -3.541018  0.887164
petal width (cm)    37.6  0.972559 -0.741520 -0.231039

In [9]:
m=len(validx)
temp2=validx.T@temp
(temp2.values/m).shape

(4, 4)

(37, 4)

In [10]:
lr.coef_.shape

(3, 4)

In [11]:
lr.intercept_

array([  9.49630591,   2.93036622, -12.42667214])

In [22]:
type(lr.predict_proba([validx.iloc[0].values])[0][0])

/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


numpy.float64

In [23]:
type(validy[0][0])

str

In [24]:
m=len(validx)
sum=0
for i in range(m):
    sum=sum+(lr.predict_proba([validx.iloc[i].values])-validy_encoded[i])

/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: 

In [39]:
validx.iloc[0].values[:]

array([6.3, 3.3, 4.7, 1.6])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 4

In [35]:
temp=np.array([1,alidx.iloc[0].values])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [34]:
temp.shape

AttributeError: 'list' object has no attribute 'shape'

In [33]:
temp@validx.iloc[0].values.T

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [26]:
sum@validx.iloc[0].values

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [ ]:
validx.values

array([[6.2, 2.8, 4.8, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [7.2, 3. , 5.8, 1.6],
       [6.8, 3.2, 5.9, 2.3],
       [6.1, 2.9, 4.7, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3. , 5. , 1.7],
       [5.6, 2.9, 3.6, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.9, 2.4, 3.3, 1. ],
       [6. , 2.7, 5.1, 1.6],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5. , 3.4, 1.6, 0.4],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 3.8, 1.7, 0.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.4, 3

In [ ]:
validy_encoded

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:

m=len(validy)
error=(lr.predict_proba(validx.values)-validy_encoded)


/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
validx.T@error

ValueError: Dot product shape mismatch, (4, 37) vs (4, 4)

In [ ]:
lr.coef_

array([[-0.31222791,  0.82129113, -2.0843139 , -0.90776664],
       [ 0.27280653, -0.31456941, -0.03202196, -0.62856078],
       [ 0.03942138, -0.50672172,  2.11633586,  1.53632742]])

ValueError: Unable to coerce to DataFrame, shape must be (4, 4): given (5, 3)

array([[ 0.04889983,  0.028505  , -0.07740483],
       [ 0.01146216,  0.02034181, -0.03180398],
       [ 0.05951697,  0.01569254, -0.07520952],
       [ 0.02334687,  0.01643729, -0.03978415]])

In [ ]:
gradient=np.array([np.ones((1,4)),gradient])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
(lr.predict_proba(validx)-validy_encoded).shape

(37, 3)

In [ ]:
validx.T.shape

(4, 37)

In [ ]:
error=validx.T@(lr.predict_proba(validx)-validy_encoded)
error.shape

ValueError: matrices are not aligned

In [ ]:
gradient.values.T

(3, 4)

In [ ]:
n_epochs= 5000
eta=0.1
for epoch in range(n_epochs):
    gradient=(validx.T@(lr.predict_proba(validx)-validy_encoded))/m
    lr.coef_= lr.coef_-eta*gradient.values.T

ValueError: matrices are not aligned

In [ ]:
theta

array([[ 7.68792829,  2.30635814, -9.99428643],
       [-0.31222791,  0.82129113, -2.0843139 ],
       [-0.90776664,  0.27280653, -0.31456941],
       [-0.03202196, -0.62856078,  0.03942138],
       [-0.50672172,  2.11633586,  1.53632742]])

array([-0.41827364,  0.9663797 , -2.52082545])

In [ ]:
m=len(validx)

temp=lr.predict_proba(validx)-validy_encoded

