<h1> Using Scikit learn

In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import add_dummy_feature
iris=load_iris(as_frame=True)
X=iris.data
Y=iris.target_names[iris.target]

In [3]:
from sklearn.model_selection import train_test_split
trainx,testx,trainy,testy= train_test_split(X,Y,test_size=0.5)
validx=testx[:len(testx)//2]
validy=testy[:len(testy)//2]
testx=testx[len(testx)//2:]
testx=testy[len(testy)//2:]

In [4]:
from sklearn.linear_model import LogisticRegression
import numpy as np
lr=LogisticRegression()

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
validy_encoded=ohe.fit_transform(validy.reshape(-1,1),)

In [7]:
lr.fit(trainx,trainy)

LogisticRegression()

In [93]:
temp=lr.predict_proba(validx)-validy_encoded


In [94]:
temp=add_dummy_feature(temp)

In [103]:
validx.T@temp

0         1         2         3
sepal length (cm)  215.8 -0.894439 -0.946184  1.840623
sepal width (cm)   115.5 -0.934508 -0.007601  0.942109
petal length (cm)  132.7  0.262941 -0.584426  0.321485
petal width (cm)    41.6  0.173801  0.275297 -0.449099

In [96]:
m=len(validx)
temp2=validx.T@temp
(temp2.values/m).shape

(4, 4)

In [87]:
lr.coef_.shape

(3, 4)

In [41]:
lr.intercept_

array([ 7.68792829,  2.30635814, -9.99428643])

In [165]:
m=len(validx)
sum=0
for i in range(m):
    sum=sum+lr.predict_proba(validx)-validy

LogisticRegression()

In [190]:
validx.values

array([[6.2, 2.8, 4.8, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [7.2, 3. , 5.8, 1.6],
       [6.8, 3.2, 5.9, 2.3],
       [6.1, 2.9, 4.7, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3. , 5. , 1.7],
       [5.6, 2.9, 3.6, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.9, 2.4, 3.3, 1. ],
       [6. , 2.7, 5.1, 1.6],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5. , 3.4, 1.6, 0.4],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 3.8, 1.7, 0.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.4, 3

In [194]:
validy_encoded

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [62]:

m=len(validy)
error=(lr.predict_proba(validx.values)-validy_encoded)


/home/prashant/Study material/WORK_SPACES/Python/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [101]:
validx.T@error

ValueError: Dot product shape mismatch, (4, 37) vs (4, 4)

In [29]:
lr.coef_

array([[-0.31222791,  0.82129113, -2.0843139 , -0.90776664],
       [ 0.27280653, -0.31456941, -0.03202196, -0.62856078],
       [ 0.03942138, -0.50672172,  2.11633586,  1.53632742]])

ValueError: Unable to coerce to DataFrame, shape must be (4, 4): given (5, 3)

array([[ 0.04889983,  0.028505  , -0.07740483],
       [ 0.01146216,  0.02034181, -0.03180398],
       [ 0.05951697,  0.01569254, -0.07520952],
       [ 0.02334687,  0.01643729, -0.03978415]])

In [189]:
gradient=np.array([np.ones((1,4)),gradient])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [79]:
(lr.predict_proba(validx)-validy_encoded).shape

(37, 3)

In [80]:
validx.T.shape

(4, 37)

In [77]:
error=validx.T@(lr.predict_proba(validx)-validy_encoded)
error.shape

ValueError: matrices are not aligned

In [75]:
gradient.values.T

(3, 4)

In [76]:
n_epochs= 5000
eta=0.1
for epoch in range(n_epochs):
    gradient=(validx.T@(lr.predict_proba(validx)-validy_encoded))/m
    lr.coef_= lr.coef_-eta*gradient.values.T

ValueError: matrices are not aligned

In [34]:
theta

array([[ 7.68792829,  2.30635814, -9.99428643],
       [-0.31222791,  0.82129113, -2.0843139 ],
       [-0.90776664,  0.27280653, -0.31456941],
       [-0.03202196, -0.62856078,  0.03942138],
       [-0.50672172,  2.11633586,  1.53632742]])

array([-0.41827364,  0.9663797 , -2.52082545])

In [ ]:
m=len(validx)

temp=lr.predict_proba(validx)-validy_encoded

